CREATE TABLE address
(
    id           INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    street_line  VARCHAR(255),
    postal_code  INTEGER,
    city         VARCHAR(255),
    county       VARCHAR(255),
    country      VARCHAR(255),
    shop_user_id INTEGER,
    CONSTRAINT pk_address PRIMARY KEY (id)
);

CREATE TABLE attribute_value
(
    id                   INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    val                  VARCHAR(255),
    product_attribute_id INTEGER,
    CONSTRAINT pk_attribute_value PRIMARY KEY (id)
);

CREATE TABLE cart
(
    id           INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    shop_user_id INTEGER,
    total_price  INTEGER,
    CONSTRAINT pk_cart PRIMARY KEY (id)
);

CREATE TABLE cart_entry
(
    id                    INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    cart_id               INTEGER,
    product_id            INTEGER,
    quantity              INTEGER,
    price_per_piece       INTEGER,
    total_price_per_entry INTEGER,
    CONSTRAINT pk_cart_entry PRIMARY KEY (id)
);

CREATE TABLE category
(
    id            INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    category_name VARCHAR(255),
    CONSTRAINT pk_category PRIMARY KEY (id)
);

CREATE TABLE product
(
    id                  INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    product_name        VARCHAR(255),
    product_description TEXT,
    price               INTEGER,
    available_quantity  INTEGER,
    added_date          date,
    category_id         INTEGER,
    CONSTRAINT pk_product PRIMARY KEY (id)
);

CREATE TABLE product_attribute
(
    id                     INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    product_attribute_name VARCHAR(255),
    CONSTRAINT pk_product_attribute PRIMARY KEY (id)
);

CREATE TABLE shop_order
(
    id               INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    shop_user_id     INTEGER,
    cart_id          INTEGER,
    payment_type     VARCHAR(255),
    delivery_address INTEGER,
    invoice_address  INTEGER,
    total_price      INTEGER,
    order_date       date,
    CONSTRAINT pk_shop_order PRIMARY KEY (id)
);

CREATE TABLE shop_order_entry
(
    id            INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    product_id    INTEGER,
    quantity      INTEGER,
    shop_order_id INTEGER,
    CONSTRAINT pk_shop_order_entry PRIMARY KEY (id)
);

CREATE TABLE shop_user
(
    id                       INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    first_name               VARCHAR(255),
    last_name                VARCHAR(255),
    email                    VARCHAR(255),
    phone_number             VARCHAR(255),
    password                 VARCHAR(255),
    default_delivery_address INTEGER,
    default_billing_address  INTEGER,
    CONSTRAINT pk_shop_user PRIMARY KEY (id)
);

CREATE TABLE valid_attribute
(
    id                   INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    product_attribute_id INTEGER,
    attribute_value_id   INTEGER,
    product_id           INTEGER,
    CONSTRAINT pk_valid_attribute PRIMARY KEY (id)
);

ALTER TABLE address
    ADD CONSTRAINT FK_ADDRESS_ON_SHOP_USER FOREIGN KEY (shop_user_id) REFERENCES shop_user (id);

ALTER TABLE attribute_value
    ADD CONSTRAINT FK_ATTRIBUTE_VALUE_ON_PRODUCT_ATTRIBUTE FOREIGN KEY (product_attribute_id) REFERENCES product_attribute (id);

ALTER TABLE cart_entry
    ADD CONSTRAINT FK_CART_ENTRY_ON_CART FOREIGN KEY (cart_id) REFERENCES cart (id);

ALTER TABLE cart_entry
    ADD CONSTRAINT FK_CART_ENTRY_ON_PRODUCT FOREIGN KEY (product_id) REFERENCES product (id);

ALTER TABLE cart
    ADD CONSTRAINT FK_CART_ON_SHOP_USER FOREIGN KEY (shop_user_id) REFERENCES shop_user (id);

ALTER TABLE product
    ADD CONSTRAINT FK_PRODUCT_ON_CATEGORY FOREIGN KEY (category_id) REFERENCES category (id);

ALTER TABLE shop_order_entry
    ADD CONSTRAINT FK_SHOP_ORDER_ENTRY_ON_PRODUCT FOREIGN KEY (product_id) REFERENCES product (id);

ALTER TABLE shop_order_entry
    ADD CONSTRAINT FK_SHOP_ORDER_ENTRY_ON_SHOP_ORDER FOREIGN KEY (shop_order_id) REFERENCES shop_order (id);

ALTER TABLE shop_order
    ADD CONSTRAINT FK_SHOP_ORDER_ON_CART FOREIGN KEY (cart_id) REFERENCES cart (id);

ALTER TABLE shop_order
    ADD CONSTRAINT FK_SHOP_ORDER_ON_DELIVERY_ADDRESS FOREIGN KEY (delivery_address) REFERENCES address (id);

ALTER TABLE shop_order
    ADD CONSTRAINT FK_SHOP_ORDER_ON_INVOICE_ADDRESS FOREIGN KEY (invoice_address) REFERENCES address (id);

ALTER TABLE shop_order
    ADD CONSTRAINT FK_SHOP_ORDER_ON_SHOPUSER FOREIGN KEY (shop_user_id) REFERENCES shop_user (id);

ALTER TABLE shop_user
    ADD CONSTRAINT FK_SHOP_USER_ON_DEFAULT_BILLING_ADDRESS FOREIGN KEY (default_billing_address) REFERENCES address (id);

ALTER TABLE shop_user
    ADD CONSTRAINT FK_SHOP_USER_ON_DEFAULT_DELIVERY_ADDRESS FOREIGN KEY (default_delivery_address) REFERENCES address (id);

ALTER TABLE valid_attribute
    ADD CONSTRAINT FK_VALID_ATTRIBUTE_ON_ATTRIBUTE_VALUE FOREIGN KEY (attribute_value_id) REFERENCES attribute_value (id);

ALTER TABLE valid_attribute
    ADD CONSTRAINT FK_VALID_ATTRIBUTE_ON_PRODUCT FOREIGN KEY (product_id) REFERENCES product (id);

ALTER TABLE valid_attribute
    ADD CONSTRAINT FK_VALID_ATTRIBUTE_ON_PRODUCT_ATTRIBUTE FOREIGN KEY (product_attribute_id) REFERENCES product_attribute (id);